server:
  port: 8080
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zwx385745/springCloudTest.git      