server:
  port: 8080
spring:
  application:
    name: paascloud-discovery
  cloud:
    config:
      server:
        git:
          uri: https://github.com/paascloud/paascloud-config-repo.git


eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@paascloud-eureka:8761/eureka/
  instance:
    prefer-ip-address: true
security:
  user:
    name: admin
    password: admin
logging:
  level.root: info
  path: logs/
  file: ${spring.application.name}.log
